/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.io.*;
import Controller.*;

/**
 *
 * @author Benji
 */
public class Owner_Main_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Owner_Main_GUI
     */
    public Owner_Main_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Vehicle_Viewer = new javax.swing.JButton();
        Booking_Viewer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Booking_Managment = new javax.swing.JButton();
        Vehicle_Managment = new javax.swing.JButton();
        User_Managment = new javax.swing.JButton();
        SignU = new javax.swing.JButton();
        PDet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Alte DIN 1451 Mittelschrift", 0, 18)); // NOI18N
        jLabel1.setText("   Tyr CR");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, null, null));

        jLabel2.setFont(new java.awt.Font("Alte DIN 1451 Mittelschrift", 0, 14)); // NOI18N
        jLabel2.setText("Owner");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Vehicle_Viewer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Vehicle_Viewer.setText("Vehicle Viewer");
        Vehicle_Viewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vehicle_ViewerActionPerformed(evt);
            }
        });

        Booking_Viewer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Booking_Viewer.setText("Manage Bookings");
        Booking_Viewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Booking_ViewerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Alte DIN 1451 Mittelschrift", 1, 18)); // NOI18N
        jLabel3.setText("Welcome: ");

        Booking_Managment.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        Booking_Managment.setText("Booking Manager");
        Booking_Managment.setToolTipText("");
        Booking_Managment.setOpaque(true);
        Booking_Managment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Booking_ManagmentActionPerformed(evt);
            }
        });

        Vehicle_Managment.setFont(new java.awt.Font("Arial", 1, 8)); // NOI18N
        Vehicle_Managment.setText("Vehicle Manager");
        Vehicle_Managment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vehicle_ManagmentActionPerformed(evt);
            }
        });

        User_Managment.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        User_Managment.setText("User Manager");
        User_Managment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_ManagmentActionPerformed(evt);
            }
        });

        SignU.setBackground(new java.awt.Color(160, 20, 30));
        SignU.setFont(new java.awt.Font("Alte DIN 1451 Mittelschrift", 1, 12)); // NOI18N
        SignU.setText("Sign Out");
        SignU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUActionPerformed(evt);
            }
        });

        PDet.setText("Personal Details");
        PDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PDet)
                .addGap(61, 61, 61)
                .addComponent(SignU))
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vehicle_Viewer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Booking_Viewer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Booking_Managment, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Vehicle_Managment, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(User_Managment, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SignU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PDet)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Booking_Managment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(Booking_Viewer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Vehicle_Viewer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Vehicle_Managment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(User_Managment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Vehicle_ManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vehicle_ManagmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vehicle_ManagmentActionPerformed

    private void User_ManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_ManagmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_User_ManagmentActionPerformed

    private void Booking_ManagmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Booking_ManagmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Booking_ManagmentActionPerformed

    private void SignUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUActionPerformed
        Open.app.Login();
    }//GEN-LAST:event_SignUActionPerformed

    private void PDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDetActionPerformed

    private void Vehicle_ViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vehicle_ViewerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vehicle_ViewerActionPerformed

    private void Booking_ViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Booking_ViewerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Booking_ViewerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Owner_Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Owner_Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Owner_Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Owner_Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner_Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Booking_Managment;
    private javax.swing.JButton Booking_Viewer;
    private javax.swing.JButton PDet;
    private javax.swing.JButton SignU;
    private javax.swing.JButton User_Managment;
    private javax.swing.JButton Vehicle_Managment;
    private javax.swing.JButton Vehicle_Viewer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
